// <auto-generated />
using System;
using GraduateThesis.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraduateThesis.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240510051701_FixedAllClubColumns")]
    partial class FixedAllClubColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GraduateThesis.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Teknoloji",
                            CreatedDate = new DateTime(2024, 5, 10, 8, 17, 1, 228, DateTimeKind.Local).AddTicks(3646)
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Spor",
                            CreatedDate = new DateTime(2024, 5, 10, 8, 17, 1, 228, DateTimeKind.Local).AddTicks(3654)
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Kitap",
                            CreatedDate = new DateTime(2024, 5, 10, 8, 17, 1, 228, DateTimeKind.Local).AddTicks(3655)
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Sanat",
                            CreatedDate = new DateTime(2024, 5, 10, 8, 17, 1, 228, DateTimeKind.Local).AddTicks(3656)
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Dans",
                            CreatedDate = new DateTime(2024, 5, 10, 8, 17, 1, 228, DateTimeKind.Local).AddTicks(3656)
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Girişimcilik",
                            CreatedDate = new DateTime(2024, 5, 10, 8, 17, 1, 228, DateTimeKind.Local).AddTicks(3657)
                        });
                });

            modelBuilder.Entity("GraduateThesis.Core.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 10, 8, 17, 1, 228, DateTimeKind.Local).AddTicks(3895),
                            IsActive = true,
                            Name = "DU Siber",
                            Summary = "DU Siber Kulübü, öğrencilere teknoloji, yazılım ve siber güvenlik alanlarında deneyim kazanma imkanı sunar. Atölyeler, yarışmalar ve seminerlerle öğrenme ortamı sağlar. Katılın, teknolojiye adım atın ve kendinizi geliştirin!",
                            Url = "default.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 10, 8, 17, 1, 228, DateTimeKind.Local).AddTicks(3897),
                            IsActive = true,
                            Name = "Kitap Dostu",
                            Summary = "Kitap Dostu Kulübü, kitap tutkunlarını bir araya getirerek edebiyatın büyülü dünyasında yolculuğa çıkarır. Okuma tutkusunu paylaşan herkesi bekliyoruz!",
                            Url = "default.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 10, 8, 17, 1, 228, DateTimeKind.Local).AddTicks(3899),
                            IsActive = true,
                            Name = "DU Archer Club",
                            Summary = "DU Archer Club, okçuluk tutkunlarının buluşma noktasıdır. Okçuluk sporuna ilgi duyan herkesi bekliyoruz! ",
                            Url = "default.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 10, 8, 17, 1, 228, DateTimeKind.Local).AddTicks(3899),
                            IsActive = true,
                            Name = "DU Scout Club",
                            Summary = "Kulübümüz, doğayla iç içe olmayı, macera dolu anlar yaşamayı seven herkesi bir araya getiriyor. Keşfetmeye hazır mısın?  ",
                            Url = "default.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 5, 10, 8, 17, 1, 228, DateTimeKind.Local).AddTicks(3900),
                            IsActive = true,
                            Name = "Elit Dans Kulübü",
                            Summary = "Elit Dans Kulübü, ritim tutmayı seven herkes için mükemmel bir buluşma noktasıdır. Eğlenceli dans dersleri ve unutulmaz performanslarla dolu bir deneyim için seni de bekliyoruz! ",
                            Url = "default.jpg"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 5, 10, 8, 17, 1, 228, DateTimeKind.Local).AddTicks(3901),
                            IsActive = true,
                            Name = "The Young Entrepreneurs Club",
                            Summary = "Genç Girişimciler Kulübü, yenilikçi fikirleriyle öne çıkan gençleri bir araya getirir. İş dünyasına adım atmak isteyenlere mentorluk yapar ve eğitimler düzenler. İş hayatına dair her şeyi keşfetmek için seni de aramıza bekliyoruz! ",
                            Url = "default.jpg"
                        });
                });

            modelBuilder.Entity("GraduateThesis.Core.Models.ClubCategory", b =>
                {
                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ClubId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ClubCategories");

                    b.HasData(
                        new
                        {
                            ClubId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ClubId = 2,
                            CategoryId = 3
                        },
                        new
                        {
                            ClubId = 3,
                            CategoryId = 2
                        },
                        new
                        {
                            ClubId = 4,
                            CategoryId = 2
                        },
                        new
                        {
                            ClubId = 5,
                            CategoryId = 5
                        },
                        new
                        {
                            ClubId = 6,
                            CategoryId = 6
                        });
                });

            modelBuilder.Entity("GraduateThesis.Core.Models.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Rector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("GraduateThesis.Core.Models.ClubCategory", b =>
                {
                    b.HasOne("GraduateThesis.Core.Models.Category", "Category")
                        .WithMany("ClubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraduateThesis.Core.Models.Club", "Club")
                        .WithMany("ClubCategories")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("GraduateThesis.Core.Models.Category", b =>
                {
                    b.Navigation("ClubCategories");
                });

            modelBuilder.Entity("GraduateThesis.Core.Models.Club", b =>
                {
                    b.Navigation("ClubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
